/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email: string;
    preferences: UserPreferences;
}
export interface UserPreferences {
    shareProgress: boolean;
    motivationalStyle: MotivationalStyle;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DayInfo {
    dayOfWeek: DayOfWeek;
    fullDate: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MotivationalSaying {
    author: string;
    message: string;
}
export interface BurnedCalorieSummary {
    dailyTotal: bigint;
    dailyEntries: Array<BurnedCalorieEntry>;
}
export interface BodyMeasurements {
    arms: number;
    bust: number;
    date: Time;
    hips: number;
    legs: number;
}
export interface DailyChecklist {
    day: DayOfWeek;
    core: Array<ExerciseEntry>;
    date: Time;
    stretching: Array<ExerciseEntry>;
    resistance: Array<ExerciseEntry>;
    cardio: Array<ExerciseEntry>;
}
export interface ProgressData {
    weeklyProgress: Array<ExerciseProgress>;
    totalCompletedExercises: bigint;
    totalCardioCompleted: bigint;
    totalStretchingCompleted: bigint;
    totalResistanceCompleted: bigint;
    totalCoreCompleted: bigint;
}
export interface ExerciseProgress {
    day: DayOfWeek;
    stretchingCompleted: bigint;
    cardioCompleted: bigint;
    resistanceCompleted: bigint;
    coreCompleted: bigint;
}
export interface BurnedCalorieEntry {
    date: Time;
    caloriesBurned: bigint;
}
export interface MoodEnergyLog {
    date: Time;
    mood: bigint;
    energy: bigint;
}
export interface WeeklyExercisePlan {
    weekStartDate: Time;
    dailyPlans: Array<DailyExercisePlan>;
}
export interface DailyExercisePlan {
    day: DayOfWeek;
    core: Array<ExerciseEntry>;
    stretching: Array<ExerciseEntry>;
    resistance: Array<ExerciseEntry>;
    cardio: Array<ExerciseEntry>;
}
export interface StreakData {
    maxStreak: bigint;
    currentStreak: bigint;
}
export interface ExerciseEntry {
    completed: boolean;
    exercise: string;
    planned: boolean;
}
export interface CalorieEntry {
    date: Time;
    calories: bigint;
}
export interface MotivationalMessage {
    date: Time;
    type: MotivationalType;
    message: string;
}
export interface ProgressPhoto {
    description: string;
    filePath: string;
    uploadDate: Time;
}
export interface WeightRecord {
    weight: number;
    date: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ProgressSummary {
    exerciseConsistency: number;
    weightLossPercentage: number;
    measurementChanges: number;
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum MotivationalStyle {
    gentle = "gentle",
    direct = "direct",
    balanced = "balanced"
}
export enum MotivationalType {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBodyMeasurement(measurement: BodyMeasurements): Promise<void>;
    addBurnedCalorieEntry(entry: BurnedCalorieEntry): Promise<void>;
    addCalorieEntry(entry: CalorieEntry): Promise<void>;
    addMoodEnergyLog(log: MoodEnergyLog): Promise<void>;
    addMotivationalMessage(message: MotivationalMessage): Promise<void>;
    addProgressPhoto(photo: ProgressPhoto): Promise<void>;
    addProgressSummary(summary: ProgressSummary): Promise<void>;
    addWeeklyExercisePlan(plan: WeeklyExercisePlan): Promise<void>;
    addWeightRecord(record: WeightRecord): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCurrentWeek(): Promise<void>;
    deleteExerciseFromChecklist(day: DayOfWeek, category: string, index: bigint): Promise<void>;
    deleteExerciseFromPlanner(weekStartDate: Time, day: DayOfWeek, category: string, index: bigint): Promise<void>;
    deleteProgressPhoto(filePath: string): Promise<void>;
    deleteWeeklyExercisePlan(weekStartDate: Time): Promise<void>;
    getBodyMeasurements(): Promise<Array<BodyMeasurements>>;
    getBurnedCalorieEntries(): Promise<Array<BurnedCalorieEntry>>;
    getBurnedCalorieSummary(): Promise<BurnedCalorieSummary>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCalorieEntries(): Promise<Array<CalorieEntry>>;
    getCurrentDayInfo(): Promise<DayInfo>;
    getDailyChecklists(): Promise<Array<DailyChecklist>>;
    getDailyMotivationalSaying(): Promise<MotivationalSaying>;
    getMoodEnergyLogs(): Promise<Array<MoodEnergyLog>>;
    getMotivationalMessages(): Promise<Array<MotivationalMessage>>;
    getProgressData(): Promise<ProgressData>;
    getProgressPhotos(): Promise<Array<ProgressPhoto>>;
    getProgressSummaries(): Promise<Array<ProgressSummary>>;
    getStreakData(): Promise<StreakData>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyExercisePlans(): Promise<Array<WeeklyExercisePlan>>;
    getWeightRecords(): Promise<Array<WeightRecord>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleExerciseCompletion(day: DayOfWeek, category: string, index: bigint): Promise<void>;
    updateBodyMeasurement(index: bigint, updatedMeasurement: BodyMeasurements): Promise<void>;
    updateCalorieEntry(index: bigint, updatedEntry: CalorieEntry): Promise<void>;
    updateWeightRecord(index: bigint, updatedRecord: WeightRecord): Promise<void>;
}
import type { DailyChecklist as _DailyChecklist, DailyExercisePlan as _DailyExercisePlan, DayInfo as _DayInfo, DayOfWeek as _DayOfWeek, ExerciseEntry as _ExerciseEntry, ExerciseProgress as _ExerciseProgress, MotivationalMessage as _MotivationalMessage, MotivationalStyle as _MotivationalStyle, MotivationalType as _MotivationalType, ProgressData as _ProgressData, Time as _Time, UserPreferences as _UserPreferences, UserProfile as _UserProfile, UserRole as _UserRole, WeeklyExercisePlan as _WeeklyExercisePlan, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBodyMeasurement(arg0: BodyMeasurements): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBodyMeasurement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBodyMeasurement(arg0);
            return result;
        }
    }
    async addBurnedCalorieEntry(arg0: BurnedCalorieEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBurnedCalorieEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBurnedCalorieEntry(arg0);
            return result;
        }
    }
    async addCalorieEntry(arg0: CalorieEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalorieEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalorieEntry(arg0);
            return result;
        }
    }
    async addMoodEnergyLog(arg0: MoodEnergyLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoodEnergyLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoodEnergyLog(arg0);
            return result;
        }
    }
    async addMotivationalMessage(arg0: MotivationalMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMotivationalMessage(to_candid_MotivationalMessage_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMotivationalMessage(to_candid_MotivationalMessage_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProgressPhoto(arg0: ProgressPhoto): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProgressPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProgressPhoto(arg0);
            return result;
        }
    }
    async addProgressSummary(arg0: ProgressSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProgressSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProgressSummary(arg0);
            return result;
        }
    }
    async addWeeklyExercisePlan(arg0: WeeklyExercisePlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeeklyExercisePlan(to_candid_WeeklyExercisePlan_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeeklyExercisePlan(to_candid_WeeklyExercisePlan_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWeightRecord(arg0: WeightRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightRecord(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCurrentWeek(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCurrentWeek();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCurrentWeek();
            return result;
        }
    }
    async deleteExerciseFromChecklist(arg0: DayOfWeek, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExerciseFromChecklist(to_candid_DayOfWeek_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExerciseFromChecklist(to_candid_DayOfWeek_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async deleteExerciseFromPlanner(arg0: Time, arg1: DayOfWeek, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExerciseFromPlanner(arg0, to_candid_DayOfWeek_n17(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExerciseFromPlanner(arg0, to_candid_DayOfWeek_n17(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteProgressPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProgressPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProgressPhoto(arg0);
            return result;
        }
    }
    async deleteWeeklyExercisePlan(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWeeklyExercisePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWeeklyExercisePlan(arg0);
            return result;
        }
    }
    async getBodyMeasurements(): Promise<Array<BodyMeasurements>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBodyMeasurements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBodyMeasurements();
            return result;
        }
    }
    async getBurnedCalorieEntries(): Promise<Array<BurnedCalorieEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBurnedCalorieEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBurnedCalorieEntries();
            return result;
        }
    }
    async getBurnedCalorieSummary(): Promise<BurnedCalorieSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getBurnedCalorieSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBurnedCalorieSummary();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCalorieEntries(): Promise<Array<CalorieEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalorieEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalorieEntries();
            return result;
        }
    }
    async getCurrentDayInfo(): Promise<DayInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentDayInfo();
                return from_candid_DayInfo_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentDayInfo();
            return from_candid_DayInfo_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyChecklists(): Promise<Array<DailyChecklist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyChecklists();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyChecklists();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyMotivationalSaying(): Promise<MotivationalSaying> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyMotivationalSaying();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyMotivationalSaying();
            return result;
        }
    }
    async getMoodEnergyLogs(): Promise<Array<MoodEnergyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEnergyLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEnergyLogs();
            return result;
        }
    }
    async getMotivationalMessages(): Promise<Array<MotivationalMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMotivationalMessages();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMotivationalMessages();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressData(): Promise<ProgressData> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressData();
                return from_candid_ProgressData_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressData();
            return from_candid_ProgressData_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressPhotos(): Promise<Array<ProgressPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressPhotos();
            return result;
        }
    }
    async getProgressSummaries(): Promise<Array<ProgressSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressSummaries();
            return result;
        }
    }
    async getStreakData(): Promise<StreakData> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakData();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyExercisePlans(): Promise<Array<WeeklyExercisePlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyExercisePlans();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyExercisePlans();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightRecords(): Promise<Array<WeightRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightRecords();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleExerciseCompletion(arg0: DayOfWeek, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleExerciseCompletion(to_candid_DayOfWeek_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleExerciseCompletion(to_candid_DayOfWeek_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateBodyMeasurement(arg0: bigint, arg1: BodyMeasurements): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBodyMeasurement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBodyMeasurement(arg0, arg1);
            return result;
        }
    }
    async updateCalorieEntry(arg0: bigint, arg1: CalorieEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalorieEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalorieEntry(arg0, arg1);
            return result;
        }
    }
    async updateWeightRecord(arg0: bigint, arg1: WeightRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeightRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeightRecord(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DailyChecklist_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyChecklist): DailyChecklist {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DailyExercisePlan_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyExercisePlan): DailyExercisePlan {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_DayInfo_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayInfo): DayInfo {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_DayOfWeek_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ExerciseProgress_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseProgress): ExerciseProgress {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_MotivationalMessage_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MotivationalMessage): MotivationalMessage {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_MotivationalStyle_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MotivationalStyle): MotivationalStyle {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MotivationalType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MotivationalType): MotivationalType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ProgressData_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgressData): ProgressData {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyExercisePlan_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyExercisePlan): WeeklyExercisePlan {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    preferences: _UserPreferences;
}): {
    name: string;
    email: string;
    preferences: UserPreferences;
} {
    return {
        name: value.name,
        email: value.email,
        preferences: from_candid_UserPreferences_n24(_uploadFile, _downloadFile, value.preferences)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shareProgress: boolean;
    motivationalStyle: _MotivationalStyle;
}): {
    shareProgress: boolean;
    motivationalStyle: MotivationalStyle;
} {
    return {
        shareProgress: value.shareProgress,
        motivationalStyle: from_candid_MotivationalStyle_n26(_uploadFile, _downloadFile, value.motivationalStyle)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dayOfWeek: _DayOfWeek;
    fullDate: string;
}): {
    dayOfWeek: DayOfWeek;
    fullDate: string;
} {
    return {
        dayOfWeek: from_candid_DayOfWeek_n32(_uploadFile, _downloadFile, value.dayOfWeek),
        fullDate: value.fullDate
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    core: Array<_ExerciseEntry>;
    date: _Time;
    stretching: Array<_ExerciseEntry>;
    resistance: Array<_ExerciseEntry>;
    cardio: Array<_ExerciseEntry>;
}): {
    day: DayOfWeek;
    core: Array<ExerciseEntry>;
    date: Time;
    stretching: Array<ExerciseEntry>;
    resistance: Array<ExerciseEntry>;
    cardio: Array<ExerciseEntry>;
} {
    return {
        day: from_candid_DayOfWeek_n32(_uploadFile, _downloadFile, value.day),
        core: value.core,
        date: value.date,
        stretching: value.stretching,
        resistance: value.resistance,
        cardio: value.cardio
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    type: _MotivationalType;
    message: string;
}): {
    date: Time;
    type: MotivationalType;
    message: string;
} {
    return {
        date: value.date,
        type: from_candid_MotivationalType_n40(_uploadFile, _downloadFile, value.type),
        message: value.message
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weeklyProgress: Array<_ExerciseProgress>;
    totalCompletedExercises: bigint;
    totalCardioCompleted: bigint;
    totalStretchingCompleted: bigint;
    totalResistanceCompleted: bigint;
    totalCoreCompleted: bigint;
}): {
    weeklyProgress: Array<ExerciseProgress>;
    totalCompletedExercises: bigint;
    totalCardioCompleted: bigint;
    totalStretchingCompleted: bigint;
    totalResistanceCompleted: bigint;
    totalCoreCompleted: bigint;
} {
    return {
        weeklyProgress: from_candid_vec_n44(_uploadFile, _downloadFile, value.weeklyProgress),
        totalCompletedExercises: value.totalCompletedExercises,
        totalCardioCompleted: value.totalCardioCompleted,
        totalStretchingCompleted: value.totalStretchingCompleted,
        totalResistanceCompleted: value.totalResistanceCompleted,
        totalCoreCompleted: value.totalCoreCompleted
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    stretchingCompleted: bigint;
    cardioCompleted: bigint;
    resistanceCompleted: bigint;
    coreCompleted: bigint;
}): {
    day: DayOfWeek;
    stretchingCompleted: bigint;
    cardioCompleted: bigint;
    resistanceCompleted: bigint;
    coreCompleted: bigint;
} {
    return {
        day: from_candid_DayOfWeek_n32(_uploadFile, _downloadFile, value.day),
        stretchingCompleted: value.stretchingCompleted,
        cardioCompleted: value.cardioCompleted,
        resistanceCompleted: value.resistanceCompleted,
        coreCompleted: value.coreCompleted
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weekStartDate: _Time;
    dailyPlans: Array<_DailyExercisePlan>;
}): {
    weekStartDate: Time;
    dailyPlans: Array<DailyExercisePlan>;
} {
    return {
        weekStartDate: value.weekStartDate,
        dailyPlans: from_candid_vec_n50(_uploadFile, _downloadFile, value.dailyPlans)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    core: Array<_ExerciseEntry>;
    stretching: Array<_ExerciseEntry>;
    resistance: Array<_ExerciseEntry>;
    cardio: Array<_ExerciseEntry>;
}): {
    day: DayOfWeek;
    core: Array<ExerciseEntry>;
    stretching: Array<ExerciseEntry>;
    resistance: Array<ExerciseEntry>;
    cardio: Array<ExerciseEntry>;
} {
    return {
        day: from_candid_DayOfWeek_n32(_uploadFile, _downloadFile, value.day),
        core: value.core,
        stretching: value.stretching,
        resistance: value.resistance,
        cardio: value.cardio
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gentle: null;
} | {
    direct: null;
} | {
    balanced: null;
}): MotivationalStyle {
    return "gentle" in value ? MotivationalStyle.gentle : "direct" in value ? MotivationalStyle.direct : "balanced" in value ? MotivationalStyle.balanced : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): MotivationalType {
    return "monthly" in value ? MotivationalType.monthly : "daily" in value ? MotivationalType.daily : "weekly" in value ? MotivationalType.weekly : value;
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyChecklist>): Array<DailyChecklist> {
    return value.map((x)=>from_candid_DailyChecklist_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MotivationalMessage>): Array<MotivationalMessage> {
    return value.map((x)=>from_candid_MotivationalMessage_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExerciseProgress>): Array<ExerciseProgress> {
    return value.map((x)=>from_candid_ExerciseProgress_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeeklyExercisePlan>): Array<WeeklyExercisePlan> {
    return value.map((x)=>from_candid_WeeklyExercisePlan_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyExercisePlan>): Array<DailyExercisePlan> {
    return value.map((x)=>from_candid_DailyExercisePlan_n51(_uploadFile, _downloadFile, x));
}
function to_candid_DailyExercisePlan_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyExercisePlan): _DailyExercisePlan {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_DayOfWeek_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_MotivationalMessage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotivationalMessage): _MotivationalMessage {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MotivationalStyle_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotivationalStyle): _MotivationalStyle {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_MotivationalType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotivationalType): _MotivationalType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserPreferences_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferences): _UserPreferences {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_WeeklyExercisePlan_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeeklyExercisePlan): _WeeklyExercisePlan {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weekStartDate: Time;
    dailyPlans: Array<DailyExercisePlan>;
}): {
    weekStartDate: _Time;
    dailyPlans: Array<_DailyExercisePlan>;
} {
    return {
        weekStartDate: value.weekStartDate,
        dailyPlans: to_candid_vec_n14(_uploadFile, _downloadFile, value.dailyPlans)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: DayOfWeek;
    core: Array<ExerciseEntry>;
    stretching: Array<ExerciseEntry>;
    resistance: Array<ExerciseEntry>;
    cardio: Array<ExerciseEntry>;
}): {
    day: _DayOfWeek;
    core: Array<_ExerciseEntry>;
    stretching: Array<_ExerciseEntry>;
    resistance: Array<_ExerciseEntry>;
    cardio: Array<_ExerciseEntry>;
} {
    return {
        day: to_candid_DayOfWeek_n17(_uploadFile, _downloadFile, value.day),
        core: value.core,
        stretching: value.stretching,
        resistance: value.resistance,
        cardio: value.cardio
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    preferences: UserPreferences;
}): {
    name: string;
    email: string;
    preferences: _UserPreferences;
} {
    return {
        name: value.name,
        email: value.email,
        preferences: to_candid_UserPreferences_n55(_uploadFile, _downloadFile, value.preferences)
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shareProgress: boolean;
    motivationalStyle: MotivationalStyle;
}): {
    shareProgress: boolean;
    motivationalStyle: _MotivationalStyle;
} {
    return {
        shareProgress: value.shareProgress,
        motivationalStyle: to_candid_MotivationalStyle_n57(_uploadFile, _downloadFile, value.motivationalStyle)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Time;
    type: MotivationalType;
    message: string;
}): {
    date: _Time;
    type: _MotivationalType;
    message: string;
} {
    return {
        date: value.date,
        type: to_candid_MotivationalType_n10(_uploadFile, _downloadFile, value.type),
        message: value.message
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotivationalType): {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == MotivationalType.monthly ? {
        monthly: null
    } : value == MotivationalType.daily ? {
        daily: null
    } : value == MotivationalType.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotivationalStyle): {
    gentle: null;
} | {
    direct: null;
} | {
    balanced: null;
} {
    return value == MotivationalStyle.gentle ? {
        gentle: null
    } : value == MotivationalStyle.direct ? {
        direct: null
    } : value == MotivationalStyle.balanced ? {
        balanced: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DailyExercisePlan>): Array<_DailyExercisePlan> {
    return value.map((x)=>to_candid_DailyExercisePlan_n15(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
